[package]
name = "xia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard-win = "4.5.0"
serde_json = "1.0.99"
urlencoding = "2.1.2"
